# This is a basic workflow to help you get started with Actions

name: My First Workflow

on:
  push:
    branches: [ "main", "01_DockerTest" ]
  pull_request:
    branches: [ "main", "01_DockerTest" ]
  workflow_dispatch:

env:
  IMAGE_NAME: hello-world-nginx
  REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/hello-world-nginx

jobs:
  first-pipeline:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # for branch and SHA tags ------
      - name: Compute image tags
        id: meta
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          SHA="${GITHUB_SHA::7}"
          echo "branch_tag=${BRANCH}" >> $GITHUB_OUTPUT
          echo "sha_tag=${SHA}" >> $GITHUB_OUTPUT

      # Log in to GHCR for pushing images
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image tagged with branch and commit-sha
      - name: Build image
        run: |
          docker build \
            -t $REGISTRY_IMAGE:${{ steps.meta.outputs.branch_tag }} \
            -t $REGISTRY_IMAGE:${{ steps.meta.outputs.sha_tag }} \
            .
